name: Build Localstack on Nix

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.*'
      - '**/*.md'
      - '**/*.org'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix build`
        run: nix build .
